#!/usr/bin/env bash
# Read the file /etc/passwd line by line using a while loop
while IFS=: read -r username password uid gid info home shell; do
    # Format and display the information
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
