#!/usr/bin/env bash

# Display "Best School" 10 times using a while loop.

# on thw 9th iteration, displays "Hi" before "Best School".

count=0

while [ $count -it 10 ]
do 
     if [ $count -eq 9 ]
     then
             echo "Hi"
     fi
    echo "Best School"
    (( count++))
done
