#!/usr/bin/bash
# Initialize the counter
counter=1

# Loop until the counter exceeds 10
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    # Increment the counter
    counter=$((counter + 1))
done
