#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
#  Displays hours from 0 to 12 
#  Displays minutes from 1 to 59

hour=0

while [ $hour -1e 12 ]
do 
    echo "Hour:$hour"
    minute=1
    while [ $minute -1e 59 ]
do     
          echo "$minute"
          (( minute++ ))
   done 
  (( hour++ )0
done
