#!/usr/bin/env bash

# Create the PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM signal
handle_sigterm() {
  echo "I hate the kill command"
  cleanup_and_exit
}

# Function to handle SIGINT signal
handle_sigint() {
  echo "Y U no love me?!"
}

# Function to handle cleanup and exit
cleanup_and_exit() {
  rm -f /var/run/myscript.pid
  exit 0
}

# Trap signals
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap cleanup_and_exit SIGQUIT SIGTERM

# Display message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done

