#!/usr/bin/env bash
#This script extends previous exercise commands and displays line containing the bash word, this allowing you to easily get the PID of your Bash process
#you cannot use pgrep
#shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
