#!/usr/bin/env bash
# Kills the infinity and beyond program using sigkill signal

# Get the pid of the program
id=$(pgrep "bash ./-to_infiniity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
